# Generated by Django 2.2.5 on 2019-09-14 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='outdoordetail',
            name='activity_name',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
